os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
env:
  matrix:
  - ARCH=x86_64 PUID=1000 PGID=1000
#   - ARCH=armhf PUID=1001 PGID=1001
  global:
  - secure: UoO+fY9m7k9IGdZO5D1JG6lv5pP1gGlCQqicAQ89zaNSXh/5d0g8S0IQq17Q7q2+IB8IftlkQgWvk6UNE1LyHtMk0PQIxuSsoU00sBvpnmeOPxaT51JJPG5X8xK+wwSSO1eJAnQJx+MlJIDERW8ot+2qeZLlD8jGXKhFAXpiZr/KB4p01sAdE13D+wNrL2kMzFkf7TADc/wOMrte8fIMtQAhBfDrH4R2qO6g2hyr8GIzpyUd0cvp9uLUuzZHssJAQkd9iPdQjdnx6gpAT2Wm+BBDLOdcr8N9mVW61jgOYYRT49oo3SNFPeHC5kruWol2FPeoE946gM7ID2Ca5vw6+bS+caZg1gH/hVab/jwKbPTVlmhC5I925h8ic01E3X5okGDCiWe9x6kflssVd/VKHoFOygjbbF2t/AlNoViGZUd+0ilo1iYMRxyGnoF9hlBVKuJhXqsiBBGRUFsEUwsG7VPJNm01P4ajOw3Vwk0ZgtT3pQXTVtlmmn3yhM/+X6+ZpH+5ySLxXfyVO8Mg7GIejM0IIueuxsiXtxmztp2OwhWQWs0JIqQ36wW0vGSlyzT38hfBXqyXKd0p0phNVXGuxtt5XJoE2LNpyhHaPNz4ZInRCPt1pG6Z9FSYlwdKQGtV8F/4CwwZFDKkxsSaKihjFPAWO1B2bldNghT8aFO8T/A=
  - secure: ICQm4U/RLDoHypNqUOEnjWLoVwmSp8BsHO42+J1oFrOVVFYJFwO+RwBN/E589dbg6W1jb8sAy2UQCugNdH7QFcrFTyytmOOewRli1Tlo0cu5ItWzA3ZiDOUImpv436oHNmaXqNKjwQ17lUbk1gyfJDRCJH54xt1MQlmgCdNJBtf8A4Us7QM8kotZj2tloJM6TLDSKtnM/iZsv/UpV3UJK5GCpU89WDZB2BZ/3slJ/h4mQAJ+gn65wEwnQRcx0MO5umnVKwwjDk6UrxOeekLrvXqE6WAWoQcUQpqY2neQzAjeMdpl0byOJRwiLjdYPO6NThjqHSm3CsHogQZA4RWTRUnXe1jdVWGMEbgQOGDtS/NY1dFKduk6YSvdV7hcTMOI45DtbYjqjZeqXJXZrySn/B9i5/c/gENR827s7Li4dj2hT8Uhc8HDbXUIvDShGIt+H/nM/XQwMmXuaZS5LDENn28KrwNU+oZBLOm/ZkdSDiXWimLWzwaeJcuoTThvB5CbG0qwTJm/VXKSwmiLoym57vVHzk3lxy8r9pzYHtS/7W+KqYks9hLSAl5VxbAxtxOSX1qryBUN7Hiv1LwmfSQFEwUz3EcaOJoxb02wWmZQJPubz9FWtJsKAmMG35nwFrNCpecVLgYKEd1v49gfBpowO23HWaMoOrlnO5Ea9GOHh2M=
install: true
before_script:
- docker --version
- make --version
script:
- make ARCH=${ARCH} PUID=${PUID} PGID=${PGID} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} push
after_script:
- docker logout
- make clean
